name: 'Setup nanoflann'
description: 'Setup workflow with nanoflann'
inputs:
  version:
    description: 'nanoflann version'
    required: false
    default: latest
branding:
  icon: 'archive'
  color: 'green'
runs:
  using: "composite"
  steps:
    - run: ${GITHUB_ACTION_PATH}/deps.sh
      shell: bash
    - run: ${GITHUB_ACTION_PATH}/entrypoint.sh ${{ inputs.version }}
      shell: bash